### ISSUE TITLE
Crash with "refId not found: " + refId

### ISSUE THREAD

**Issue by serjek** [colyseus/colyseus-haxe#42]
Comes from `Schema.hx`:424. 
Happens during inconsistent state when reconnecting to the room.

Happens on nodejs, RN and sys environments, and frequently reproduced when client leaves the room and tries to join again some seconds later, without using reconnect flow.

**Comment by endel** [comment]
Hi @serjek, thanks for reporting! 

This sounds bad, can you share briefly how was your schema state when this happened? (`this.state.toJSON()` from server-side)

**Comment by serjek** [comment]
Sure, next time it happens. Perhaps it would be safer to just post a warning instead of crashing the whole app? ;)

**Comment by endel** [comment]
Thanks! This error is very important tho, it shouldn't **ever** happen, that means the client-side would have inconsistent state because of decoding issues

**Comment by serjek** [comment]
Did a quick research: it happens during `room.leave(true)` before `room.connection.onClose` handler is triggered. Perhaps there is a state update happens at this time and it clashes with room state being emptied.

I recall I got those errors quite frequent in RN but didn't give them priority because they crash just a closure (that is already due to dispose) and did not break anything. This happened only when I leave the room.

**Comment by endel** [comment]
Your research was correct! 🙈 very silly mistake on my end, [the `.teardown()` call](https://github.com/colyseus/colyseus-haxe/commit/ff9f2d36a13716f6c854ba095edaff17cba12eca) was immediately removing all cached references (`refId`'s) from the serializer, and the error happened when a patch arrived between requesting to close the connection while having all local `refId`'s cleared out.

Now the teardown happens [only after `connection.onClose`](https://github.com/colyseus/colyseus-haxe/blob/b47469426bd19408300e4ebf19e84139e89c16aa/src/io/colyseus/Room.hx#L54)

Thanks for your patience and for reporting @serjek! Version 0.14.8 is available with the fix!
