### ISSUE TITLE
Schema.listen() not implemented

### ISSUE THREAD

**Issue by sh-dave** [colyseus/colyseus-haxe#47]
While following your [tic tac toe](https://github.com/endel/colyseus-tic-tac-toe/blob/5f94a79ab0e5ecbba7e4955df060cd5801e96ad3/javascript-pixi/src/screens/GameScreen.js#L53) example i noticed that the haxe version doesn't provide the [Schema.listen](https://github.com/colyseus/schema/blob/d3ce63db3ca6a8e1c3f5dbdd60bd7d71c416d8c8/src/Schema.ts#L180) function. Looking that one up revealed a [note](https://github.com/colyseus/schema/blob/d3ce63db3ca6a8e1c3f5dbdd60bd7d71c416d8c8/src/Schema.ts#L135) about refactoring the code in the first place. Is this the refactoring still on a todo list, or should it just be ported to haxe as is if possible?

**Comment by endel** [comment]
Hi @sh-dave, currently `.listen()` is still only supported in JavaScript. We haven't figured out a way to have a `.listen()` functionality on other compiled languages like Haxe and C# yet 😭

**Comment by endel** [comment]
This has been implemented on 0.15
