### ISSUE TITLE
Type not Found Error

### ISSUE THREAD

**Issue by Raam124** [colyseus/colyseus-haxe#48]
Main.hx:1: characters 8-30 : Type not found : io.colyseus.Client
Main.hx:2: characters 8-24 : Type not found : io.colyseus.Room
Main.hx:4: characters 18-24 : Type not found : Client

I'm doing exactly how the document says but still getting these errors

**Comment by serjek** [comment]
Turns out you didn't install the library properly. Make sure you run `haxelib install colyseus` before running example.

**Comment by Raam124** [comment]
I've installed it properly and still getting this

**Comment by DillyzThe1** [comment]
Your problem is not that you have not installed the library, but rather you seem to have not <b>imported</b> it.
Go to Project.xml & put the following next to the other libraries:
```xml
<haxelib name="colyseus" />
```
