### ISSUE TITLE
Warning : Std.is is deprecated. Use Std.isOfType instead.

### ISSUE THREAD

**Issue by Raam124** [colyseus/colyseus-haxe#49]
while running the code shown in https://docs.colyseus.io/colyseus/getting-started/haxe-client/

**Comment by serjek** [comment]
1. which haxe version do you use?
2. where this error exactly comes from? please post a full stack trace.

**Comment by endel** [comment]
Fixed on 0.15 https://github.com/colyseus/colyseus-websocket-hx/commit/82cac588a1fe44fb5667e2b12b3c9232ccd5e260
