### ISSUE TITLE
Is there a simple way to compile Haxe client code into CPP code?

### ISSUE THREAD

**Issue by mmssddss** [colyseus/colyseus-haxe#56]
I want to use colyseus in my cpp project, and there is no official cpp client
so I want to compile haxe client to cpp
Is this feasible? Are there any best practices?

**Comment by endel** [comment]
Hi @mmssddss, I think there are two options:

- compile the Colyseus Haxe SDK as a cpp library (not sure how to do that!)
- use a cpp-ported library, there's one made by the community for Unreal Engine here: https://github.com/charisma-ai/colyseus-unreal (although schema support is outdated there)

**Comment by mmssddss** [comment]
https://github.com/charisma-ai/colyseus-unreal 
Can this library only support the Unreal engine, or can it be used for any CPP engine project?

**Comment by endel** [comment]
That one is specific to Unreal Engine. I'm afraid there's no general-purpose cpp client out there, the closest to that would be compiling the haxe SDK to cpp - which would include the whole haxe stdlib into your project...

**Comment by endel** [comment]
Closing as a non-issue, best place for questions is Discord or https://github.com/orgs/colyseus/discussions
